### ISSUE TITLE
Pio::FlowModについて

### ISSUE THREAD

**Issue by shun159** [trema/pio#114]
※誤りありましたらすみません…

このようなデータを与え、````Match.new````をしました。

```` ruby
{:in_port=>1,
 :dl_src=>"00:00:00:00:00:0a",
 :dl_dst=>"00:00:00:00:00:14",
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>"10.0.0.0/8",
 :nw_dst=>"20.0.0.0/8",
 :tp_src=>8,
 :tp_dst=>0}

pp Match.new match
{:wildcards=>
  [:dl_vlan, :tp_dst, {:nw_src=>24}, {:nw_dst=>24}, :dl_vlan_pcp, :nw_tos],
 :in_port=>1,
 :dl_src=>#<Pio::Mac:21221080 "00:00:00:00:00:0a">,
 :dl_dst=>#<Pio::Mac:21217820 "00:00:00:00:00:14">,
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>
  #<Pio::IPv4Address:0x00000002882230
   @value=#<IPAddr: IPv4:10.0.0.0/255.255.255.255>>,
 :nw_dst=>
  #<Pio::IPv4Address:0x00000002880138
   @value=#<IPAddr: IPv4:20.0.0.0/255.255.255.255>>,
 :tp_src=>8,
 :tp_dst=>0}
````
Trema::Matchでは以下のとおりとなりますので、
wildcardsの表示が違うように見えます。
````
ruby
> match =  Match.new( {:in_port=>1, :dl_src=>"00:00:00:00:00:0a", :dl_dst=>"00:00:00:00:00:14", :dl_vlan=>0, :dl_vlan_pcp=>0, :dl_type=>2048, :nw_tos=>0, :nw_proto=>1, :nw_src=>"10.0.0.0/8", :nw_dst=>"20.0.0.0/8", :tp_src=>8, :tp_dst=>0} )
> match.to_s
 => "wildcards = 0x61800(nw_src(24)|nw_dst(24)), in_port = 1, dl_src = 00:00:00:00:00:0a, dl_dst = 00:00:00:00:00:14, dl_vlan = 0, dl_vlan_pcp = 0, dl_type = 0x800, nw_tos = 0, nw_proto = 1, nw_src = 10.0.0.0/8, nw_dst = 20.0.0.0/8, tp_src = 8, tp_dst = 0"
````
となっております。

また、以下をするとRuntimeErrorを起こします。

```` ruby
match =  Match.new( {:in_port=>1, :dl_src=>"00:00:00:00:00:0a", :dl_dst=>"00:00:00:00:00:14", :dl_vlan=>0, :dl_vlan_pcp=>0, :dl_type=>2048, :nw_tos=>0, :nw_proto=>1, :nw_src=>"10.0.0.0/8", :nw_dst=>"20.0.0.0/8", :tp_src=>8, :tp_dst=>0} )
 match_bin = match.to_binary_s
# => RuntimeError: Invalid flag: {:nw_src=>24}
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/pio-0.10.1/lib/pio/match.rb:70:in `block in set'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/pio-0.10.1/lib/pio/match.rb:69:in `each'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/pio-0.10.1/lib/pio/match.rb:69:in `set'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/primitive.rb:98:in `do_write'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in `block in do_write'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in `each'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in `do_write'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/base.rb:167:in `write'
        from /usr/local/rvm/gems/ruby-2.0.0-p598/gems/bindata-2.1.0/lib/bindata/base.rb:180:in `to_binary_s'
        from (irb):5
        from /usr/local/rvm/rubies/ruby-2.0.0-p598/bin/irb:12:in `<main>'
````
また、FlowMod.readについて、バイナリデータを作成し
readさせました。出力は以下のとおりです。
※　IPアドレスのマスクが反映されていないように見えます
```` ruby
bianry =  [1,14,0,192,0,0,0,0,0,6,24,0,0,1,0,0,0,0,0,10,0,0,0,0,0,20,0,0,0,0,8,0,0,1,0,0,10,0,0,0,20,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,255,255,255,255,0,1,0,1,0,8,0,10,0,0,0,2,0,8,0,0,0,0,0,3,0,8,0,0,0,0,0,4,0,16,0,0,0,0,0,1,0,0,0,0,0,0,0,5,0,16,0,0,0,0,0,2,0,0,0,0,0,0,0,6,0,8,10,0,0,1,0,7,0,8,20,0,0,2,0,8,0,8,184,0,0,0,0,9,0,8,0,8,0,0,0,10,0,8,0,0,0,0,0,11,0,16,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,8,0,1,0,128].pack("C*")

pp FlowMod.read bianry
#<Pio::FlowMod:0x00000002a50620
 @format=
  {:open_flow_header=>
    {:ofp_version=>1,
     :message_type=>14,
     :message_length=>192,
     :transaction_id=>0},
   :body=>
    {:match=>
      {:wildcards=>[{:nw_src=>24}, {:nw_dst=>24}],
       :in_port=>1,
       :dl_src=>#<Pio::Mac:21891620 "00:00:00:00:00:0a">,
       :dl_dst=>#<Pio::Mac:21845160 "00:00:00:00:00:14">,
       :dl_vlan=>0,
       :dl_vlan_pcp=>0,
       :dl_type=>2048,
       :nw_tos=>0,
       :nw_proto=>1,
       :nw_src=>
        #<Pio::IPv4Address:0x000000029a8c18
         @value=#<IPAddr: IPv4:10.0.0.0/255.255.255.255>>,
       :nw_dst=>
        #<Pio::IPv4Address:0x00000002987860
         @value=#<IPAddr: IPv4:20.0.0.0/255.255.255.255>>,
       :tp_src=>8,
       :tp_dst=>0},
     :cookie=>0,
     :command=>:add,
     :idle_timeout=>0,
     :hard_timeout=>0,
     :priority=>65535,
     :buffer_id=>4294967295,
     :out_port=>65535,
     :flags=>[:send_flow_rem],
     :actions=>
      [#<Pio::SetVlanVid:0x00000002984700
        @format={:type=>1, :message_length=>8, :vlan_id=>10}>,
       #<Pio::SetVlanPriority:0x00000002979558
        @format={:type=>2, :message_length=>8, :vlan_priority=>0}>,
       #<Pio::StripVlanHeader:0x00000002962218
        @format={:type=>3, :message_length=>8}>,
       #<Pio::SetEthSrcAddr:0x0000000295fae0
        @format=
         {:type=>4,
          :message_length=>16,
          :mac_address=>#<Pio::Mac:21685520 "00:00:00:00:00:01">}>,
       #<Pio::SetEthDstAddr:0x00000002957e80
        @format=
         {:type=>5,
          :message_length=>16,
          :mac_address=>#<Pio::Mac:21668840 "00:00:00:00:00:02">}>,
       #<Pio::SetIpSrcAddr:0x00000002954190
        @format=
         {:type=>6,
          :message_length=>8,
          :ip_address=>
           #<Pio::IPv4Address:0x00000002940988
            @value=#<IPAddr: IPv4:10.0.0.1/255.255.255.255>>}>,
       #<Pio::SetIpDstAddr:0x0000000292fb38
        @format=
         {:type=>7,
          :message_length=>8,
          :ip_address=>
           #<Pio::IPv4Address:0x0000000292b5b0
            @value=#<IPAddr: IPv4:20.0.0.2/255.255.255.255>>}>,
       #<Pio::SetIpTos:0x0000000292aae8
        @format={:type=>8, :message_length=>8, :type_of_service=>184}>,
       #<Pio::SetTransportSrcPort:0x0000000291b4f8
        @format={:type=>9, :message_length=>8, :port_number=>8}>,
       #<Pio::SetTransportDstPort:0x0000000290b170
        @format={:type=>10, :message_length=>8, :port_number=>0}>,
       #<Pio::Enqueue:0x00000002908f60
        @format=
         {:type=>11, :message_length=>16, :port_number=>1, :queue_id=>1}>,
       #<Pio::SendOutPort:0x000000028fde30
        @format=
         {:type=>0, :message_length=>8, :port_number=>1, :max_len=>128}>]}}>

**Comment by yasuhito** [comment]
ありがとうございます。`Pio::Match` の `:wildcards` は値は合ってると思いますが、パーサの `:nw_src` で `Pio::IPv4Address` を使ってるのでいらないマスク情報 (255.255.255.255) が入ってしまいました。`ofp_match` での型は `uint32_t` なので、マスク情報はいらないですね。RunTime Error についてもちょっと見てみます。

**Comment by shun159** [comment]
> マスク情報はいらない

ちなみに、wildcardsに保存されているマスク情報を````Pio::IPv4Address````
newするときに利用してやる感じでしょうか？

**Comment by yasuhito** [comment]
a196c9f で RuntimeError も含め直してみました。マスクも入るようにしてあります。いかがでしょうか?

**Comment by shun159** [comment]
ありがとう御座います。

大丈夫そうです！

```` ruby
match =  Match.new( {:in_port=>1, :dl_src=>"00:00:00:00:00:0a", :dl_dst=>"00:00:00:00:00:14", :dl_vlan=>0, :dl_vlan_pcp=>0, :dl_type=>2048, :nw_tos=>0, :nw_proto=>1, :nw_src=>"10.0.0.0/8", :nw_dst=>"20.0.0.0/8", :tp_src=>8, :tp_dst=>0} )

pp match
{:wildcards=>
  {:dl_vlan=>true,
   :tp_dst=>true,
   :nw_src=>24,
   :nw_dst=>24,
   :dl_vlan_pcp=>true,
   :nw_tos=>true},
 :in_port=>1,
 :dl_src=>#<Pio::Mac:19452100 "00:00:00:00:00:0a">,
 :dl_dst=>#<Pio::Mac:19442780 "00:00:00:00:00:14">,
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>
  #<Pio::IPv4Address:0x000000025160d8
   @value=#<IPAddr: IPv4:10.0.0.0/255.0.0.0>>,
 :nw_dst=>
  #<Pio::IPv4Address:0x00000002504bf8
   @value=#<IPAddr: IPv4:20.0.0.0/255.0.0.0>>,
 :tp_src=>8,
 :tp_dst=>0}
````

**Comment by shun159** [comment]
ただ、まだ`.read`した時反映されてないですね。

```` ruby
 pp match =  Match.new( {:in_port=>1, :dl_src=>"00:00:00:00:00:0a", :dl_dst=>"00:00:00:00:00:14", :dl_vlan=>0, :dl_vlan_pcp=>0, :dl_type=>2048, :nw_tos=>0, :nw_proto=>1, :nw_src=>"10.0.0.0/8", :nw_dst=>"20.0.0.0/8", :tp_src=>8, :tp_dst=>0} )
{:wildcards=>
  {:dl_vlan=>true,
   :tp_dst=>true,
   :nw_src=>24,
   :nw_dst=>24,
   :dl_vlan_pcp=>true,
   :nw_tos=>true},
 :in_port=>1,
 :dl_src=>#<Pio::Mac:23438160 "00:00:00:00:00:0a">,
 :dl_dst=>#<Pio::Mac:23384200 "00:00:00:00:00:14">,
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>
  #<Pio::IPv4Address:0x00000002c98d60
   @value=#<IPAddr: IPv4:10.0.0.0/255.0.0.0>>,
 :nw_dst=>
  #<Pio::IPv4Address:0x00000002c977d0
   @value=#<IPAddr: IPv4:20.0.0.0/255.0.0.0>>,
 :tp_src=>8,
 :tp_dst=>0}

match_bin = match.to_binary_s
 => "\x006\x18\x82\x00\x01\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\b\x00\x00\x01\x00\x00\n\x00\x00\x00\x14\x00\x00\x00\x00\b\x00\x00"

pp Match.read match_bin
{:wildcards=>
  {:dl_vlan=>true,
   :tp_dst=>true,
   :nw_src=>24,
   :nw_dst=>24,
   :dl_vlan_pcp=>true,
   :nw_tos=>true},
 :in_port=>1,
 :dl_src=>#<Pio::Mac:23798380 "00:00:00:00:00:0a">,
 :dl_dst=>#<Pio::Mac:23796900 "00:00:00:00:00:14">,
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>
  #<Pio::IPv4Address:0x00000002d629f8
   @value=#<IPAddr: IPv4:10.0.0.0/255.255.255.255>>,
 :nw_dst=>
  #<Pio::IPv4Address:0x00000002d61e40
   @value=#<IPAddr: IPv4:20.0.0.0/255.255.255.255>>,
 :tp_src=>8,
 :tp_dst=>0}
````

**Comment by shun159** [comment]
あと、間違えていたらすみません。
wildcardsについてですが、

今、この実装では 各フィールドに0 もしくは すべて0のアドレスについて、
ignoreするようになっていますが、これオプションに指定されなかった場合に
ignoreにすべきではないでしょうか？また、IPアドレスについてはprefixlenが0の場合にignoreする
んじゃないかとおもいます

認識間違えありましたらすみませんが、
よろしくお願いします。

**Comment by yasuhito** [comment]
ありがとうございます。これ ↑ でどうでしょうか??

**Comment by shun159** [comment]
ありがとう御座います！
大丈夫そうでした。

````ruby
flow_mod = IO.read "features/packet_data/flow_mod_add_detailed.raw"

 pp FlowMod.read flow_mod
#<Pio::FlowMod:0x000000019e8f08
 @format=
  {:open_flow_header=>
    {:ofp_version=>1,
     :message_type=>14,
     :message_length=>192,
     :transaction_id=>0},
   :body=>
    {:match=>
      {:wildcards=>{:nw_src=>24, :nw_dst=>24},
       :in_port=>1,
       :dl_src=>#<Pio::Mac:13529560 "00:00:00:00:00:0a">,
       :dl_dst=>#<Pio::Mac:13527980 "00:00:00:00:00:14">,
       :dl_vlan=>0,
       :dl_vlan_pcp=>0,
       :dl_type=>2048,
       :nw_tos=>0,
       :nw_proto=>1,
       :nw_src=>
        #<Pio::IPv4Address:0x000000019b3560
         @value=#<IPAddr: IPv4:10.0.0.0/255.0.0.0>>,
       :nw_dst=>
        #<Pio::IPv4Address:0x000000019ab9f0
         @value=#<IPAddr: IPv4:20.0.0.0/255.0.0.0>>,
       :tp_src=>8,
       :tp_dst=>0},
     :cookie=>0,
     :command=>:add,
     :idle_timeout=>0,
     :hard_timeout=>0,
     :priority=>65535,
     :buffer_id=>4294967295,
     :out_port=>65535,
     :flags=>[:send_flow_rem],
     :actions=>
      [#<Pio::SetVlanVid:0x000000019aa7a8
        @format={:type=>1, :message_length=>8, :vlan_id=>10}>,
       #<Pio::SetVlanPriority:0x000000019a8db8
        @format={:type=>2, :message_length=>8, :vlan_priority=>0}>,
       #<Pio::StripVlanHeader:0x000000019a3340
        @format={:type=>3, :message_length=>8}>,
       #<Pio::SetEthSrcAddr:0x000000019a1cc0
        @format=
         {:type=>4,
          :message_length=>16,
          :mac_address=>#<Pio::Mac:13433600 "00:00:00:00:00:01">}>,
       #<Pio::SetEthDstAddr:0x0000000199ef20
        @format=
         {:type=>5,
          :message_length=>16,
          :mac_address=>#<Pio::Mac:13427880 "00:00:00:00:00:02">}>,
       #<Pio::SetIpSrcAddr:0x0000000199c1d0
        @format=
         {:type=>6,
          :message_length=>8,
          :ip_address=>
           #<Pio::IPv4Address:0x000000019924a0
            @value=#<IPAddr: IPv4:10.0.0.1/255.255.255.255>>}>,
       #<Pio::SetIpDstAddr:0x00000001991d20
        @format=
         {:type=>7,
          :message_length=>8,
          :ip_address=>
           #<Pio::IPv4Address:0x0000000197bd90
            @value=#<IPAddr: IPv4:20.0.0.2/255.255.255.255>>}>,
       #<Pio::SetIpTos:0x0000000197ac88
        @format={:type=>8, :message_length=>8, :type_of_service=>184}>,
       #<Pio::SetTransportSrcPort:0x00000001978c80
        @format={:type=>9, :message_length=>8, :port_number=>8}>,
       #<Pio::SetTransportDstPort:0x0000000196b328
        @format={:type=>10, :message_length=>8, :port_number=>0}>,
       #<Pio::Enqueue:0x00000001969140
        @format=
         {:type=>11, :message_length=>16, :port_number=>1, :queue_id=>1}>,
       #<Pio::SendOutPort:0x00000001966468
        @format=
         {:type=>0, :message_length=>8, :port_number=>1, :max_len=>128}>]}}>

flow_mod = IO.read "features/packet_data/flow_mod_add.raw"

pp FlowMod.read flow_mod
#<Pio::FlowMod:0x000000015f65d0
 @format=
  {:open_flow_header=>
    {:ofp_version=>1,
     :message_type=>14,
     :message_length=>80,
     :transaction_id=>21},
   :body=>
    {:match=>
      {:wildcards=>
        {:dl_vlan=>true,
         :dl_src=>true,
         :dl_dst=>true,
         :dl_type=>true,
         :nw_proto=>true,
         :tp_src=>true,
         :tp_dst=>true,
         :nw_src_all=>true,
         :nw_dst_all=>true,
         :dl_vlan_pcp=>true,
         :nw_tos=>true},
       :in_port=>1,
       :dl_src=>#<Pio::Mac:11478160 "00:00:00:00:00:00">,
       :dl_dst=>#<Pio::Mac:11467940 "00:00:00:00:00:00">,
       :dl_vlan=>0,
       :dl_vlan_pcp=>0,
       :dl_type=>0,
       :nw_tos=>0,
       :nw_proto=>0,
       :nw_src=>
        #<Pio::IPv4Address:0x00000001447a68
         @value=#<IPAddr: IPv4:0.0.0.0/255.255.255.255>>, # OFPFW_NW_SRC_ALLなら/0にすべき？
       :nw_dst=>
        #<Pio::IPv4Address:0x0000000143b060
         @value=#<IPAddr: IPv4:0.0.0.0/255.255.255.255>>,　# OFPFW_NW_DST_ALLなら/0にすべき？
       :tp_src=>0,
       :tp_dst=>0},
     :cookie=>1,
     :command=>:add,
     :idle_timeout=>0,
     :hard_timeout=>0,
     :priority=>65535,
     :buffer_id=>4294967295,
     :out_port=>2,
     :flags=>[:send_flow_rem, :check_overwrap],
     :actions=>
      [#<Pio::SendOutPort:0x000000015d9d40
        @format=
         {:type=>0, :message_length=>8, :port_number=>2, :max_len=>65535}>]}}>

pp match =  Match.new( {:in_port=>1, :dl_src=>"00:00:00:00:00:0a", :dl_dst=>"00:00:00:00:00:14", :dl_vlan=>0, :dl_vlan_pcp=>0, :dl_type=>2048, :nw_tos=>0, :nw_proto=>1, :nw_s
rc=>"10.0.0.0/8", :nw_dst=>"20.0.0.0/8", :tp_src=>8, :tp_dst=>0} )
#<Pio::Match:0x000000016d4a10
 @format=
  {:wildcards=>{:nw_src=>24, :nw_dst=>24},
   :in_port=>1,
   :dl_src=>#<Pio::Mac:11931420 "00:00:00:00:00:0a">,
   :dl_dst=>#<Pio::Mac:11928560 "00:00:00:00:00:14">,
   :dl_vlan=>0,
   :dl_vlan_pcp=>0,
   :dl_type=>2048,
   :nw_tos=>0,
   :nw_proto=>1,
   :nw_src=>
    #<Pio::IPv4Address:0x000000016b9508
     @value=#<IPAddr: IPv4:10.0.0.0/255.0.0.0>>,
   :nw_dst=>
    #<Pio::IPv4Address:0x000000016b29d8
     @value=#<IPAddr: IPv4:20.0.0.0/255.0.0.0>>,
   :tp_src=>8,
   :tp_dst=>0}>

match_bin = match.to_binary_s
 => "\x00\x06\x18\x00\x00\x01\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\b\x00\x00\x01\x00\x00\n\x00\x00\x00\x14\x00\x00\x00\x00\b\x00\x00"

pp Match.read match_bin
{:wildcards=>{:nw_src=>24, :nw_dst=>24},
 :in_port=>1,
 :dl_src=>#<Pio::Mac:11735780 "00:00:00:00:00:0a">,
 :dl_dst=>#<Pio::Mac:11734040 "00:00:00:00:00:14">,
 :dl_vlan=>0,
 :dl_vlan_pcp=>0,
 :dl_type=>2048,
 :nw_tos=>0,
 :nw_proto=>1,
 :nw_src=>
  #<Pio::IPv4Address:0x0000000165adc8
   @value=#<IPAddr: IPv4:10.0.0.0/255.0.0.0>>,
 :nw_dst=>
  #<Pio::IPv4Address:0x00000001658aa0
   @value=#<IPAddr: IPv4:20.0.0.0/255.0.0.0>>,
 :tp_src=>8,
 :tp_dst=>0}
````

**Comment by yasuhito** [comment]
では明日あたり、リファクタリングしてから新バージョンリリースしますー。

**Comment by shun159** [comment]
よかったです！
何かお手伝いできることありましたらまたおねがいしますー
